/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FxButton: typeof import('./../src/components/fx-button/index.vue')['default']
    FxCell: typeof import('./../src/components/fx-cell/index.vue')['default']
  }
}
